=head1 NAME


createnhelix - create non stationary helix filter


=head1 SYNOPSIS


C<aa=createnhelix(nd,center,gap,na,patch)>

=head1 INPUT PARAMETERS


=over 4

=item nd      - C<integer(:)>

      size of data

=item center  - C<integer(:)>

      location of the 1 of the filter within na box

=item gap     - C<integer(:)>

      distance along each axis before filter coef

=item na      - C<integer(:)>

      size of box arround filter

=item patch   - C<integer(:)>

      what model point a given filter will act on

=back

=head1 RETURN VALUE


=over 4

=item aa       - C<type(nfilter)>

      Helix filter

=back

=head1 DESCRIPTION


Create a non-stationary helix filter

=head1 SEE ALSO


L<createhelix>,L<nhelix>,L<createmshelix>

=head1 LIBRARY


B<geef90>

=cut

