=head1 NAME


csmult - complex multiplication


=head1 SYNOPSIS


C<val= csmult(c, s)>

=head1 INPUT PARAMETERS


=over 4

=item   c - complex  

        complex input

=item   s -  float   

        float values to multiply by

=back

=head1 RETURN VALUES


=over 4

=item  val- complex 

       result of multiplication

=back

=head1 DESCRIPTION

    Multiply complex number by real scalar
     Csmul returns c*s.


=head1 SEE ALSO


L<cmult>


=head1 LIBRARY


B<sepmath>

=cut

