=head1 NAME


hconest - convolution using helix filters, adjoint is filter

=head1 SYNOPSIS


Initializer - C<call hconest_init(x,aa)>

Operator    - C<ierr=hconest_lop(adj,add,xx,yy)>

=head1 PARAMETERS


=over 4

=item x  - C<real(:)>

      data

=item aa - type(filter)

      helix filter to perform convolution with

=item adj,add,xx,yy -

      standard operators parameters

=back

=head1 DESCRIPTION


  Masked helix convolution, adjoint is the filter$

=head1 SEE ALSO


L<helix>,L<nhconest>,L<helicon>,L<polydiv>

=head1 LIBRARY


B<geef90>

=cut

