=head1 NAME


helderiv - helix derivative filter

=head1 SYNOPSIS


Initializer: C<call helderiv_init(n1,na)>

Operator   : C<ierr=helderiv_lop(adj,add,pp,qq)>

Close      : C<call helderiv_close()>

=head1 PARAMETERS


=over 4

=item  n1 -  int

       number of samples in n1

=item  na -  int

       number of coefs for filter

=item adj -  logcal

      wheter or not run the adjoint

=item add -  logical

       whether or not to add outout to data

=item pp  -  C<real(:)>

      model

=item qq  -  C<real(:)>

      data

=back

=head1 DESCRIPTION


 Create and apply a helix derivative filter


=head1 SEE ALSO


L<lapfac>, L<helicon>

=head1 LIBRARY


B<geef90>

=cut

