=head1 NAME


helixcartmod - convert to and from cartesian/helix space

=head1 SYNOPSIS


C<call helix2cart(nn,i,ii)>

C<call cart2helix(nn,ii,i)>

=head1 PARAMETERS


=over 4

=item n - <int(:)>

          cartesian axes

=item ii - <int(:)>

      cartesian coordinates

=item i  - int

      helix coordinate

=back

=head1 DESCRIPTION


 Convert to and from a helix coordinate system.

=head1 LIBRARY


B<geef90>

=cut

