=head1 NAME


hwt_trace_rays - trace rays

=head1 SYNOPSIS


C<int hwt_trace_rays(int *n,float *o,float *d,float *shot,float aimi,float aima,
 float oi,float si,int ni, float sa, int na,float st,int nt,float *vel,
 float *xray,float *yray,float *zray,float *vray)>

=head1 INPUT PARAMETERS


=over 4

=item n -  int[3]    

      Dimensions of elements in velocity cube (3)

=item o -  float[3]  

      First element of velocity cube (3)

=item d -  float[3] 

      Sampling of velocity cube velocity cube (3)

=item shot -  float[3] 

      Location of shot

=item aimi -  float    

      Inclination

=item aima -  float    

      Azimuth

=item oi -  float    

      First aperture angle

=item si -  float    

      Sampling  of aperture

=item ni -  int      

      Number of half aperture angles

=item sa -  float    

      Sampling of radial steps

=item na -  int      

      Number of radial steps

=item st -  float    

      Sampling in time

=item nt -  int      

      Number of time samples

=item vel -  float*   

      Velocity

=back

=head1 OUTPUT PARAMETERS


=over 4

=item xray -  float*   

      X position of ray

=item yray -  float*   

      Y position of ray

=item zray -  float*   

      Z position of ray

=item vray -  float*   

      Velocity of ray at positon

=back

=head1 DESCRIPTION


Trace rays using Huegyn wavefrom raytracing

=head1 SEE ALSO


L<hwt_travel_cube>, L<Hwt3d>

=head1 LIBRARY


B<septravel>

=cut

