=head1 NAME


lint1 - linear 1D interpolation

=head1 SYNOPSIS


Initializer : C<call lint1_init(o1,d1,coordinate)>

Operator    : C<ierr=lint1_lop(adj,add,model,data)>

=head1 PARAMETERS


=over 4

=item o1 -  real

      first sample of model space

=item d1 -  real

      sampling of model space

=item coordinte - C<real(:)>

      location of data

=item adj,add,model,data -

       standard operator

=back

=head1 DESCRIPTION


1-D linear interpolation

=head1 SEE ALSO


L<binpull2>,L<binpull1>,L<lint2>

=head1 LIBRARY


B<geef90>

=cut

