=head1 NAME


make_unpipe - unpipe a seplib file (therefore back seakable)

=head1 SYNOPSIS


make_unpipe(tag)

=head1 INPUT PARAMETERS


=over 4

=item tag - char* 

      tag to unpipe

=back


=head1 DESCRIPTION


Make sure that a seplib input dataset is not a pipe.
If it isn't a pipe we do nothing.
If it is we make a temporary dataset and then
copy the data to a new file which is made temporary by
unlinking it after it has been created. This ensures that it
will disappear when the job ends.


=head1 COMMENTS


WARNING DO NOT CLOSE THE FILE AFTER make_unpipe() has been called 

=head1 LIBRARY

B<sep>

=cut

