=head1 NAME


partan - partan step

=head1 SYNOPSIS


C<call partan_close()>

C<ierr=partan(forget,x,g,rr,gg)>


=head1 PARAMETERS


=over 4

=item forget - logical

      Wheter or not to forget previous step

=item x      - C<real(:)>

      Model

=item g      - C<real(:)>

      Gradient

=item rr      - C<real(:)>

=item gg      - C<real(:)>

=back

=head1 DESCRIPTION


One step of partan method

=head1 SEE ALSO


L<cgmeth>, L<cdstep>,L<solver_reg>,L<conjgrad>

=head1 LIBRARY


B<geef90>

=cut

