=head1 NAME


sep3d_distribute_headers - Distribute the headers


=head1 SYNOPSIS


C<logic= sep3d_distribute_headers(struct_in,struct_out)>

=head1 INPUT PARAMETERS


=over 4

=item struct_in  -  sep3d

      structure

=item struct_out  -  sep3d

      structure

=back

=head1 DESCRIPTION


 Spread the headers of struct_in to the various sections of struct_out

=head1 SEE ALSO



=head1 LIBRARY


B<supersetf90>

=cut

