=head1 NAME


sep3dc_set_key_vals - Set header values based on keyinex



=head1 SYNOPSIS


C<logic= sep3dc_set_index(sep3dc *space1, int key, float *headers)>



=head1 INPUT PARAMETERS


=over 4

=item  space1  -  sep3d

     structure 

=item  key  -  int

     The keyindex

=item  headers  -  float*

     Header values

=back

=head1 DESCRIPTION



Set header values based on the keyindex

=head1 SEE ALSO



=head1 LIBRARY


B<superset>

=cut

