=head1 NAME


sep3d_set_coords - Specify the coordinates of a dataset in memory


=head1 SYNOPSIS


C<logic= sep3d_set_coords(struct,coords)>

=head1 INPUT PARAMETERS


=over 4

=item struct  -  sep3d

      structure

=item coords  -  int(:,:)

      coordinates

=back

=head1 DESCRIPTION


Set the coordinates of the dataset in memory

=head1 SEE ALSO



=head1 LIBRARY


B<supersetf90>

=cut

