=head1 NAME


sep_copy_gff - copy grid format file  from one SEP3d file to another

=head1 SYNOPSIS


   #include <sep3d.h>
   int sep_copy_gff(char *tag_in, char *tag_out)

=head1 PARAMETER


=over 4

=item    char *tag_in : 

         tag of input History File


=item    char *tag_out : 

         tag of output History File

=back

=head1 RETURN VALUE


 0 if successful

 +1 if tag_history is an Sep77 History File

 -1 if fails for other reasons

=head1 DESCRIPTION


Copy gff

=head1 SEE ALSO


L<sep_copy_hff>

=head1 LIBRARY


B<sep3d>

=cut

