=head1 NAME


separg - return the ith command linea argument

=head1 SYNOPSIS


C<ierr seperr(int iarg,char *arg)>

=head1 INPUT PARAMETERS


=over 4

=item	iarg -  int 

      Argument number

=item	char* -  arg 

     Arrgument

=back

=head1 RETURN VALUES


=over 4

=item	0 -  int 

      Success

=item	1 -  int 

     Requested an argument # greater than separgc

=item	-1 -  int 

      Other failure

=back


=head1 DESCRIPTION


This function returns a command line argument by
number. It makes this assumption that the string
has been allocated.

=head1 KEYWORDS



=head1 LIBRARY


B<sep>

=cut

