=head1 NAME


steering - 2-D steering filters

=head1 SYNOPSIS


C<call steer_init(hwidth,amp,n1)>

C<call steering2(slope,aa)>

=head1 PARAMETERS


=over 4

=item hwidth - real

      half-width of triangle

=item amp    - real

      amplitude that all coefs sum to

=item n1     - integer

      Axis 1 length

=item slope  - real

      slope to make filter destroy

=item aa     - type(filter)

      Helix filter

=back

=head1 DESCRIPTION


Create a single steering filter

=head1 LIBRARY


B<geef90>

=cut

