=head1 NAME


velsimp - simple velocity transfrom

=head1 SYNOPSIS


C<call velsimp( adj,add, t0,dt,x0,dx,s0,ds, nt,nx,ns, modl, data)>

=head1 INPUT PARAMETERS


=over 4

=item adj   - int

      0- (slow->offset), 1- (offset->slow)

=item add   - int

      0- erase output, 1 save output

=item t0    - real

      Initial time

=item dt    - real

      Sampling in time

=item x0    - real

      First offset

=item dx    - real

      Offset sampling

=item s0    - real

      First slowness

=item ds    - real

      Sampling in slowness

=item nt    - int

      Number of time samples

=item nx    - int

      Number of offset

=item ns    - int

      Number of slownesses

=item modl  - real(nt,ns)

      time,slowness panel

=item data - real(nt,nx)

      time,offset panel

=back

=head1 DESCRIPTION


A fortran77 program to convert from time,slowness to time, offset


=head1 LIBRARY


B<sepvelanf>

=cut

