=head1 NAME


weihcig - Perform offset domain imaging

=head1 SYNOPSIS


 ierr=weihcig(wfld,iws,ith)

=head1 PARAMETERS


=over 4

=item iws - integer

  current frequency slice

=item ith - integer

  current thread

=item wfld - complex(:,:,:,:,:)

  wavefield

=back

=head1 DESCRIPTION


 Imaging operation when in the offset domain


=head1 LIBRARY


sepweif90

=head1 SEE ALSO


 L<weihcig_init> L<weipcig>

=cut

