=head1 NAME


Hypint - velocity space transform

=head1 SYNOPSIS


Hypint conj=0 inv=0 vmin=1.4 vmax=3.0 n2= < in.H > out.H

=head1 DESCRIPTION


Velocity space transformation using INTEGRATION.
The conjugate operator is hyperbola superposition.
pseudo-unitary weighting with offset and velocity.
includes causal filter sqrt(i omega)
uniform intervals of slowness.
nearest neighbor interpolation.

=head1 INPUT PARAMETERS


=over 4

=item  conj -   integer

      [0]  adjoint

=item  inv  -   integer

      [0]  inverse

=item  vmin -   real

      [1.4]  minimum velocity

=item  vmax -   real

      [3.0]  maximum velocity

=item n1,n2,n3-integer

      standard seplib parameters

=item o1,o2,o3-real

      standard seplib parameters

=item d1,d2,d3-real

      standard seplib parameters

=back

=head1 COMMENTS


conj=0 & inv=0 operator itself
conj=1 & inv=0 conjugate transpose
conj=0 & inv=1 pseudoinverse
conj=1 & inv=1 conjugate-transpose-pseudoinverse


=head1 SEE ALSO


L<Hypmovie>


=head1 CATEGORY


B<seis/velan>

=cut

