=head1 NAME


Kirch_2d_depth - Kirchhoff 2D migration

=head1 SYNOPSIS


Kirch_2d_depth  <in.H >out.H tfile=tfile.H  pars


=head1 INPUT PARAMETERS


=over 4

=item stdin	  -	sepfile

    File for input seismic traces (must be a sep3d file)

=item stdout	 - sepfile

    File for common offset migration output  (	sep regular cube)

=item ttfile	 -	sepfile

   File for input traveltime tables. First axis is Z, second axis X, third

    axis is regular spaced source locations. If not provided will be

   calculated.

=item velfile	 -	sepfile

   Velocity file (only needed if travel time file not provided).

=item dxm  -  float

   [d3 of grid] Sampling interval of input midpoints 		

=item fzo  - float

  z-coordinate of first point in output trace 	

=item dzo - float

  vertical spacing of output trace 		

=item nzo -  int

  number of points in output trace			

=item fmax - float

  [0.25/dt]		frequency-highcut for input traces		

=item aperx - float

  [nxt*dxt/2]  	migration lateral aperature 			

=item angmax - float

 [60]		migration angle aperature from vertical 	

=item v0  - float

  [1500](m/s)		reference velocity value at surface			

=item dvz - float

 [0.0]  		reference velocity vertical gradient		

=item  ls  -int 

 [1]	                flag for line source				

=item  verb  - int

  [0]   Whether or not to be verbose

=item  max_size  - int

  [100]  Approximate maximum memory to use


=back

=head1 DESCRIPTION


Performs 2D Kirchoff depth migraion. 

=head1 NOTES


1. Output regular grid is the basis of the output cmp_x and offset_x

   parameters. The input dataset should be sep3d gridded data.

   Axis 1 - time, axis 2 - trace_in_bin, axis3-cmp_x, axis4 - offset_x .

   The header keys offset_x and cmp_x must exist in the dataset.

2. This is SU's sukdmig2d code with only very slight modifications.

   All credit belongs to  CWP.  If you use it in a paper

   make sure to credit them.

3. Only works meters/feet for some reason???

4. Traveltime tables were generated by program rayt2d (or other ones)	

   on relatively coarse grids, with dimension ns*nxt*nzt. In the	

   migration process, traveltimes are interpolated into shot/gephone 	

   positions and output grids.					',

5. If the offset value of an input trace is not in the offset array 	

   of output, the nearest one in the array is chosen. 		

6. Memory requirement for this program is about			

   	[ns*nxt*nzt+noff*nxo*nzo+4*nr*nzt+5*nxt*nzt+npa*(2*ns*nxt*nzt   

+noff*nxo*nzo+4*nxt*nzt)]*4 bytes				

   where nr = 1+min(nxt*dxt,0.5*offmax+aperx)/dxo. 			

6. Amplitudes are computed using the reference velocity profile, v(z),

   specified by the parameters v0= and dvz=.				

=head1 AUTHOR


   Zhenyue Liu, 03/01/95,  Colorado School of Mines 

=head1 CATEGORY


B<seis/image>


=cut

