=head1 NAME


Nmo3d - NMO in sep3d datasets

=head1 SYNOPSIS


Nmo3d  <in.H >out.H pars
Nmo3dM  intag=in.H outtag=out.H pars

=head1 INPUT PARAMETERS


=over 4

=item  verb   -  integer

       [0] Whether (1) or not(0) to be verbose

=item  linear -  integer

       [1] Do linear interpolation NMO, [0] Nearest neighbor

=item  adj    -  integer

       [0] Perform adjoint opperation(1), forward(0)

=item  inv    -  integer

       [0] Perform inverse(1), else forward(0)

=item  maxsize-  integer

       [10]Number of megabytes of traces to hold

=item  slowfile- sepfile

       Slowness file (regular cube or sep3d with headers)

=item  velfile-  sepfile

       Velocity file (regular cube or sep3d with headers)

=item  slow   -  float

       Slowness to do NMO on

=item  vel    -  float

       [1.5] Velocity to do constant velocity NMO

=item  off_keys- integer(:)

       Offset float key(s) describing

=item  off_axes- integer(:)

       Offset axes

=item  vel_key-  integer

       Key that relates SEP3d velocity file to SEP3d data

=item  data_keys- integer

       Key that relate SEP3d data file file velocity file

=item  data_axes int*

       Axes that relate SEP3d data file file velocity file

=item  vel_axes- int*

       Offset axis/axes that relate to the off_axes or
       offkeys of the dataset.

=item  master_data- int

       Whether or not the master trace has any of the data sections (only
       valid for Nmo3dM)

=back



=head1 DESCRIPTION


  Performs NMO, adjoint NMO, pseudoinverse NMO

=head1 SEE ALSO


L<NMO>, L<Velan3d>

=head1 COMMENTS


 off_keys and off_axes, are somewhat optional
 If none of these are suplied checks keys and then axes for
 aoffset, offset_x, and offset_y.

 If you supply a key number > key number of data_record_number subtract 1
 to the parameter (data_record_number is not stored with the headers)

=head1 CATEGORY


B<seis/velan>

=cut

