
FCALLSCFUN5(INT,arrayreadf,ARRAYREADF,arrayreadf,PSTRING,PSTRING,INT,PFLOAT,FLOAT)
FCALLSCFUN3(INT,do_sep_loop,DO_SEP_LOOP,do_sep_loop,STRING,PINT,PINT)
FCALLSCFUN4(INT,init_loop_calc,INIT_LOOP_CALC,init_loop_calc,INT,PINT,STRING,INT)
FCALLSCFUN3(INT,do_sep_loop,DO_SEP_LOOP_,do_sep_loop_,STRING,PINT,PINT)
FCALLSCFUN4(INT,init_loop_calc,INIT_LOOP_CALC_,init_loop_calc_,INT,PINT,STRING,INT)

FCALLSCFUN2(INT,compare_c,COMPARE_C,compare_c,PSTRING,PSTRING)
FCALLSCFUN4(INT,time_window,TIME_WINDOW,time_window,INT,PFLOAT,PFLOAT,PSTRING)
FCALLSCFUN2(INT,parcat,PARCAT,parcat,PSTRING,INT)
FCALLSCFUN8(INT,pad_it,PAD_IT,padit,PVOID,PVOID,INT,PINT,PINT,PINT,INT,INT)
FCALLSCFUN5(INT,arrayreadf,ARRAYREADF_,arrayreadf_,PSTRING,PSTRING,INT,PFLOAT,FLOAT)
FCALLSCFUN5(INT,arrayreadi,ARRAYREADI_,arrayreadi_,PSTRING,PSTRING,INT,PINT,INT)
FCALLSCFUN2(INT,compare_c,COMPARE_C_,compare_c_,PSTRING,PSTRING)
FCALLSCFUN2(INT,parcat,PARCAT_,parcat_,PSTRING,INT)
FCALLSCFUN4(INT,time_window,TIME_WINDOW_,time_window_,INT,PFLOAT,PFLOAT,PSTRING)



