#include "cfortran.h"
#include <sepfilter.h>

FCALLSCFUN4(INT,mksinc,MKSINC,mksinc,PFLOAT,INT,FLOAT,PFLOAT);
FCALLSCFUN5(INT,toep,TOEP,toep,INT,PFLOAT,PFLOAT,PFLOAT,PFLOAT);


/*FCALLSCFUN18(INT,hwt_trace_rays,HWT_TRACE_RAYS_,hwt_trace_rays_,PINT,PFLOAT,PFLOAT,PFLOAT,FLOAT,FLOAT,FLOAT,FLOAT,INT,FLOAT,INT,FLOAT,INT,PFLOAT,PFLOAT,PFLOAT,PFLOAT,PFLOAT)*/


FCALLSCFUN4(INT,mksinc,MKSINC_,mksinc_,PFLOAT,INT,FLOAT,PFLOAT);
FCALLSCFUN5(INT,toep,TOEP_,toep_,INT,PFLOAT,PFLOAT,PFLOAT,PFLOAT);

