/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Initpar */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Initpar
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Initpar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Initpar
 * Method:    initpar
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Initpar_initpar
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
