/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_HelixCart */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_HelixCart
#define _Included_edu_stanford_sep_seplib_corelibs_sep_HelixCart
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
