/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_GetNumberAxes */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_GetNumberAxes
#define _Included_edu_stanford_sep_seplib_corelibs_sep_GetNumberAxes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_GetNumberAxes
 * Method:    sep_get_number_data_axes
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_GetNumberAxes_sep_1get_1number_1data_1axes
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
