/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Auxputch */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Auxputch
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Auxputch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Auxputch
 * Method:    auxputch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Auxputch_auxputch__Ljava_lang_String_2Ljava_lang_String_2_3ILjava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring, jintArray, jstring);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Auxputch
 * Method:    auxputch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[FLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Auxputch_auxputch__Ljava_lang_String_2Ljava_lang_String_2_3FLjava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring, jfloatArray, jstring);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Auxputch
 * Method:    auxputch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Auxputch_auxputch__Ljava_lang_String_2Ljava_lang_String_2_3DLjava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring, jdoubleArray, jstring);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Auxputch
 * Method:    auxputch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Auxputch_auxputch__Ljava_lang_String_2Ljava_lang_String_2_3BLjava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
