/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Sreed */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Sreed
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Sreed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Sreed
 * Method:    sreed
 * Signature: (Ljava/lang/String;[BI)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Sreed_sreed__Ljava_lang_String_2_3BI
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Sreed
 * Method:    sreed
 * Signature: (Ljava/lang/String;[II)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Sreed_sreed__Ljava_lang_String_2_3II
  (JNIEnv *, jclass, jstring, jintArray, jint);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Sreed
 * Method:    sreed
 * Signature: (Ljava/lang/String;[FI)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Sreed_sreed__Ljava_lang_String_2_3FI
  (JNIEnv *, jclass, jstring, jfloatArray, jint);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Sreed
 * Method:    sreed
 * Signature: (Ljava/lang/String;[DI)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Sreed_sreed__Ljava_lang_String_2_3DI
  (JNIEnv *, jclass, jstring, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
