/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Hclose */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Hclose
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Hclose
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Hclose
 * Method:    hclose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Hclose_hclose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
