/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Redin */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Redin
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Redin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Redin
 * Method:    redin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Redin_redin
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
