/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Redout */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Redout
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Redout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Redout
 * Method:    redout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Redout_redout
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
