/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_GetPutAxis */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_GetPutAxis
#define _Included_edu_stanford_sep_seplib_corelibs_sep_GetPutAxis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_GetPutAxis
 * Method:    sep_get_data_axis_par
 * Signature: (Ljava/lang/String;[I[I[F[F[B)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_GetPutAxis_sep_1get_1data_1axis_1par
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jfloatArray, jfloatArray, jbyteArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_GetPutAxis
 * Method:    sep_put_data_axis_par
 * Signature: (Ljava/lang/String;[I[I[F[F[B)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_GetPutAxis_sep_1put_1data_1axis_1par
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jfloatArray, jfloatArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
