/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Srite */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Srite
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Srite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Srite
 * Method:    srite
 * Signature: (Ljava/lang/String;[BI)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Srite_srite__Ljava_lang_String_2_3BI
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Srite
 * Method:    srite
 * Signature: (Ljava/lang/String;[II)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Srite_srite__Ljava_lang_String_2_3II
  (JNIEnv *, jclass, jstring, jintArray, jint);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Srite
 * Method:    srite
 * Signature: (Ljava/lang/String;[FI)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Srite_srite__Ljava_lang_String_2_3FI
  (JNIEnv *, jclass, jstring, jfloatArray, jint);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Srite
 * Method:    srite
 * Signature: (Ljava/lang/String;[DI)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Srite_srite__Ljava_lang_String_2_3DI
  (JNIEnv *, jclass, jstring, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
