/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Doc */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Doc
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Doc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Doc
 * Method:    doc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Doc_doc
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
