/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Putlin */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Putlin
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Putlin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Putlin
 * Method:    putlin
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Putlin_putlin
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
