/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Datapath */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Datapath
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Datapath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Datapath
 * Method:    datapath
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Datapath_datapath
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
