/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_SriteWindow */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_SriteWindow
#define _Included_edu_stanford_sep_seplib_corelibs_sep_SriteWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_SriteWindow
 * Method:    srite_window
 * Signature: (Ljava/lang/String;I[I[I[I[II[B)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_SriteWindow_srite_1window__Ljava_lang_String_2I_3I_3I_3I_3II_3B
  (JNIEnv *, jclass, jstring, jint, jintArray, jintArray, jintArray, jintArray, jint, jbyteArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_SriteWindow
 * Method:    srite_window
 * Signature: (Ljava/lang/String;I[I[I[I[II[I)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_SriteWindow_srite_1window__Ljava_lang_String_2I_3I_3I_3I_3II_3I
  (JNIEnv *, jclass, jstring, jint, jintArray, jintArray, jintArray, jintArray, jint, jintArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_SriteWindow
 * Method:    srite_window
 * Signature: (Ljava/lang/String;I[I[I[I[II[F)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_SriteWindow_srite_1window__Ljava_lang_String_2I_3I_3I_3I_3II_3F
  (JNIEnv *, jclass, jstring, jint, jintArray, jintArray, jintArray, jintArray, jint, jfloatArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_SriteWindow
 * Method:    srite_window
 * Signature: (Ljava/lang/String;I[I[I[I[II[D)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_SriteWindow_srite_1window__Ljava_lang_String_2I_3I_3I_3I_3II_3D
  (JNIEnv *, jclass, jstring, jint, jintArray, jintArray, jintArray, jintArray, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
