/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Getch */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Getch
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Getch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Getch
 * Method:    getch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Getch_getch__Ljava_lang_String_2Ljava_lang_String_2_3I
  (JNIEnv *, jclass, jstring, jstring, jintArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Getch
 * Method:    getch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[F)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Getch_getch__Ljava_lang_String_2Ljava_lang_String_2_3F
  (JNIEnv *, jclass, jstring, jstring, jfloatArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Getch
 * Method:    getch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[D)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Getch_getch__Ljava_lang_String_2Ljava_lang_String_2_3D
  (JNIEnv *, jclass, jstring, jstring, jdoubleArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Getch
 * Method:    getch
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Getch_getch__Ljava_lang_String_2Ljava_lang_String_2_3B
  (JNIEnv *, jclass, jstring, jstring, jbyteArray);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Getch
 * Method:    getch_add_string
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Getch_getch_1add_1string
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
