/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Ssize */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Ssize
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Ssize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Ssize
 * Method:    ssize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Ssize_ssize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Ssize
 * Method:    ssize_block
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Ssize_ssize_1block
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
