/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_sep_seplib_corelibs_sep_Noheader */

#ifndef _Included_edu_stanford_sep_seplib_corelibs_sep_Noheader
#define _Included_edu_stanford_sep_seplib_corelibs_sep_Noheader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_sep_seplib_corelibs_sep_Noheader
 * Method:    noheader
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_stanford_sep_seplib_corelibs_sep_Noheader_noheader
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
