#ifndef FUNC_RICK
#define FUNC_RICK 2
extern int UIZoomStart (Widget widget,XButtonEvent *event);
extern void AnoInit ();
extern void AnoDraw (int pik0,int draw);
extern void AnoOval (int x1,int y1,int x2,int y2,int draw);
extern void AnoBox (int *x0,int *y0,int draw);
extern void Cnvrt2sep(int x,int y);
extern void AnoPolyline(int *x0,int *y0,int npts,int arrow,int draw);
extern void AnoText(int *x0,int *y0,char *mys,int rotate,int size,int draw);
extern void AnoModify(int x,int y);
extern int AnoNear (int x,int y);
extern int AnoCoord (int ipik,Plane plane,int *x,int *y);
extern void AnoAdd (int x,int y);
extern void AddAnoOval(int x1,int y1,int x2,int y2);
extern void RunGrowPik(int x1,int y1,int x2, int y2);
extern void RunAutoPik(int x1,int y1,int x2, int y2);
extern void ErasePikWindow(int x1,int y1,int x2, int y2);
extern void AddAnoRect(int x1,int y1,int x2,int y2);
extern void AddAnoTextPt(int x,int y);
extern void DeletePolyAno();
extern void FinishPolyAno();
extern void grow_region(float min_tol, float max_tol, float dtol,int nseed, Pik *seeds, int *grown, int *min, int *max);
extern void PikGrow3d();
/* typed returns */
extern Axis AxisInit (char *tag, int iaxis,int stride,int* data2D);
extern Axis AxisInit2 (int dir,int stride,string label,int size,float first,float delta, float zoom);
extern void AxisSetScale (Axis axis);
extern int AxisPrec (Axis axis);
extern int AxisScale (Axis axis);
extern void AxisSetValues (Axis axis);
extern int AxisSize (Axis axis);
extern float AxisDelta (Axis axis);
extern float AxisFirst (Axis axis);
extern float AxisLast (Axis axis);
extern float AxisZoom (Axis axis);
extern char* AxisLabel (Axis axis);
extern int AxisStride (Axis axis);
extern float AxisValue (Axis axis, int index);
extern char* AxisScript (Axis axis, int index);
extern float* AxisValues (Axis axis);
extern int AxisIndex (Axis axis,float );
extern int AxisScaledIndex (Axis axis,int value);
extern int AxisDir (Axis axis);
extern void AxisInfo (Axis axis);
extern void AxisSavePar(Axis axis);
extern void ColorInit ();
extern void ColorSwitch ();
extern void ColorSetContrast (int contrast);
extern void ColorSetContrast0 (int contrast0);
extern void ColorSetBackground (int index);
extern void ColorSetOverlay (int index);
extern void ColorSetChoice (int color);
extern int ColorSize ();
extern void ColorSetMark (int index);
extern void ColorInfo ();
extern int ColorBackground ();
extern void ColorLoad (Color cdata);
extern int ColorMark ();
extern int ColorBase ();
extern void ColorSavePar ();
extern void ColorLoadVeldata ();
extern int ColorTableDump ();

extern void ColorbarInit ();
extern void ColorbarDraw ();
extern void ColorbarOverlay ();
extern void ColorbarSetMark (int low,int high,int index);
extern void ColorbarMark (int *low,int *high,int index);
extern void DataInit( );
extern Data InitData(char *,int);
extern Anolist InitAnolist();
extern char* DataTitle(Data );
extern char* DataFile (Data );
extern char* DataShortName (Data);
extern void DataGetPar(Data data, char *tag, char *extra);
extern void CheckData();
extern void DataLoad();
extern void DataLoadByte(Data data,char *tag);
extern void DataLoadFloat(Data data,char *tag);
extern float  DataCent(float *x, int n,float p);
extern char* DataLabel(Data data);
extern char* DataTitle(Data data);
extern char* DataFile(Data data);
extern char* DataShortName(Data data);
extern char* DataFile(Data data);
extern Buffer DataBuffer(Data data);
extern Buffer return_buffer(Data data);
extern Axis DataAxis(Data data, int iaxis);
extern int DataSize(Data data);
extern int DataMaxDim(Data data);
extern float DataValue(Data data, int value);
extern int DataValueSize(Data data);
extern int DataValueBase(Data data);
extern float DataLow ();
extern float DataHigh ();
extern int DataHistogram();
extern void DataComputeHistogram();
extern int DataInfo(Data data);
extern int DataValueInfo(Data data);
extern int DataSavePar(Data data);
extern int DataDumpBytes (Data data,char *file,int fd);
extern int DataDumpHeader (Data data,string file,int datafd,int esize);
extern int DataDumpFloats (Data data,char *file,int fd);
extern void Data2Float (Buffer dbuf,float *fbuf,int n,float *min,float *max);
extern int rint2 (float x);

/** velocity view functions **/
extern Buffer VelViewBuffer(Data data);
extern void VelViewSetBuffer(int choice);
extern void VelViewSetParam(int param);
extern int VelViewParam();
extern int VelViewNum();
extern int VelViewLoaded();
extern int VelViewOn();

/** path view functions **/
extern int PathViewUpdatePicks();
extern int PathViewToggle();
extern int PathViewView();
extern Buffer PathViewBuffer(Data data, int pathDir);
extern int PathViewClose();
extern int PathViewMoveStart();
extern int PathViewMoveEnd();
extern int PathViewMoveMiddle();
extern int PathViewMoveIncrement();
extern int PathViewMoveDecrement();
extern int PathViewMoveCoordinates(float* y, float* x, float* z);
extern int PathViewAddFile();
extern int PathViewPathNum();
extern long PathViewLength();

/** math functions **/
extern void FindBufferMax(Buffer buffer, long long size, int* max);
extern void FindBufferMean(Buffer buffer, long long size, int* mean);
extern void Histogram(Buffer buffer, long long size, float* hist, int* mode);
extern float MaxVectorGap(float* vec, long length);
extern float MeanVectorGap(float* vec, long length);
extern void SplineThree(float* original, float* result, long length);
extern int* IVector(long nl, long nh);
extern void FreeIVector(int* v, long nl, long nh);
extern float* Vector(long nl, long nh);
extern void FreeVector(float* v, long nl, long nh);
extern float** Matrix(long nrl, long nrh, long ncl, long nch);
extern void FreeMatrix(float** m, long nrl, long nrh, long ncl, long nch);
extern void SplineInterp(float* xa, float* ya, float* y2a, long n, float x, float* y);
extern void Spline(float* x, float* y, long n, float yp1, float ypn, float* y2);

extern int EditFrame (Buffer data,Map map1,Map map2,Map map3,int frame,float*);
extern int EditBox (Buffer data,Map map1,Map map2,Map map3,float *dist);
extern int EditStats (int n,float *dist,int *low,int *median,int *high) ;
extern int EditCube (Buffer data,Map map1,Map map2,Map map3,float *dist);
extern int EditGrade (Buffer data,Map map1,Map map2,Map map3);
extern int EditUndo (Buffer data);
extern Map MapInit (Axis axis,string name,int imap);
extern void MapSet (Map map,Axis axis,int size,int first,int last,int frame1,int frame2,int dframe);

extern int MapBound (int index,int bound1,int bound2);
extern void MapSetSize (Map map,int size);
extern void MapSetTics (Map map);
extern void MapSwap (Map a,Map b);
extern void MapFlip (Map map);
extern Axis MapAxis (Map map);
extern char* MapName (Map map);
extern Vec MapVec (Map map);
extern Vec MapInterp (Map map);
extern int MapSize (Map map);
extern int MapWindow (Map map);
extern int MapZoom (Map map);
extern int MapFirst (Map map);
extern int MapLast (Map map);
extern int MapLow (Map map);
extern int MapHigh (Map map);
extern int MapFrame (Map map);
extern int MapFrame1 (Map map);
extern int MapNFrame (Map map);
extern int MapPrev (Map map);
extern int MapSave (Map map);
extern float MapTic0 (Map map);
extern float MapTic2 (Map map);
extern int MapNtic (Map map);
extern float MapDtic (Map map);
extern int MapMovie1 (Map map);
extern int MapMovie2 (Map map);
extern int MapDmovie (Map map);
extern char* MapFormat (Map map);
extern void MapSetFrame (Map map,int frame);
extern void MapSetFrameBounds (Map map,int frame1,int frame2);
extern void MapSetDmovie (Map map,int dframe);
extern void MapSetFrame1 (Map map,int frame);
extern void MapNextFrame (Map map);
extern int MapInverse (Map map,int index);
extern int MapMap (Map map,int index);
extern int MapIndex (Map map,float value);
extern float MapValue (Map map,int index);
extern int MapSavePar (Map map);
extern int MapInfo (Map map);
extern void MapRestoreFrame (Map map);
extern void MapSaveFrame (Map map);
extern int MapDump (Map map);

extern void MovieInit();
extern int MovieDir();
extern void MovieSetDir (int dir);
extern void MovieToggleDir ();
extern int MovieToggleCache ();
extern int MovieCache ();
extern int MovieDelay ();
extern int MovieSetRun (int run);
extern int MovieRun ();
extern int MovieMulti();
extern int SetMovieMulti(int multi);
extern int MovieDeltaSpeed (int speed);
extern int MovieSetSpeed (int speed);
extern int MovieGetSpeed ();
extern int MovieOn ();
extern int MovieOff ();
extern int MovieInfo ();
extern int MovieSavePar ();
extern void PickInit();
extern int PickDecode (int x,int y,PickPoint pick,int print);
extern void PickDecodeShadow (Shadow_ shadow,int *index);
extern PickLine PickFind(int dir3,int frame3,int dir4,int frame4,int dir5,int frame5);
extern int PickSize ();
extern int PickAxis();
extern int PickDir (PickLine pickline);
extern int PickCount (PickLine pickline);
extern int PickIndex (PickLine pickline,int,int);
extern int PickFrame (int ipick);
extern int PickInfo ();
extern void PickAdd (int x,int y);
extern void PickInsert (int x,int y);
extern void PickReplace (int x,int y);
extern void PickDelete (int x,int y);
extern void PickDraw (PickLine pickline,int draw);
extern void PickDrawAll (int draw);
extern void PickRead ();
extern void PickWrite ();
extern void PickClear (PickLine pickline);
extern void PickClear0 ();
extern int PickSetFrame(int index);
extern void PickSavePar ();
extern void PickListInfo ();
extern int PickSameFrame (PickPoint pick1,PickPoint pick2);
extern int PickSameDir (PickPoint pick1,PickPoint pick2);
extern int PickSharedDir (PickPoint pick1,PickPoint pick2);
extern int PickBetween (int *a,int *b,int *c);
extern void PikInit();
extern int MovieSavePar ();
extern void PikDraw (int pik0,int draw);
extern void PikDrawSymb (int x,int y,int draw,char symbol);
extern void PikDrawBox (int x,int y,int size,int draw);
extern int  PikNear (int x,int y);
extern int PikCoord (int ipik,Plane plane,int *x,int *y);
extern int PikQuery (int x,int y);
extern void PikAdd (int x,int y);
extern void PikDelete (int x,int y);
extern void delete_point (int inear);
extern int PikUndo ();
extern int PikInfo ();
extern int PikSave ();
extern int PikIncreaseSize (void);
extern int PikDecreaseSize (void);
extern int PikIncreaseRange (void);
extern int PikDecreaseRange (void);

/* typed returns */
extern Plane PlaneInit();
extern Plane PlaneFind (int dir3,int frame3,int dir4,int frame4,int dir5,int frame5,int check_pickable);
extern void PlaneReset ();
extern void PlaneSet (Map hmap,Map vmap,Map zmap,Map map4,Map map5,int h0,int v0,int nh,int nv,Render render,int *margins,RenderAttr attr,int pickable);
void float_to_byte(float *input, Buffer output, int n1, float *tgain, register float bias, register float scale, int value_size);
void compute_gain_pars(Data data,  float *buf2, int n, register float *scale, register float *bias );
int x_y_from_pik_plane(Pik pik, Plane plane, int *xout, int *yout);
void PlaneSetFrame (Plane plane,int frame3);
extern int PlaneDir (Plane plane);
extern int PlaneFrame (Plane plane);
extern void PlaneRect (int *h0,int *v0,int *nh,int *nv);
extern int PlaneType (Plane plane);
extern int PlaneSkew (Plane plane);
extern int PlaneV0 (Plane plane);
extern int PlaneH0 (Plane plane);
extern int PlaneNV (Plane plane);
extern int PlaneNH (Plane plane);
extern Map PlaneHmap (Plane plane);
extern Map PlaneVmap (Plane plane);
extern Map PlaneZmap (Plane plane);
/* Region used by X11/Intrinsic.h */

extern int RegionSetLive (int live);
extern int RegionSetBound (int index,int ibound);
extern int RegionSetNeighborhood (int mode);
extern int RegionSetSeed (int *seed);
extern int RegionBound (int ibound);
extern int RegionSize ();
extern int RegionMark0 ();
extern int RegionFill (int *seed,int bound1,int bound2,int value);
extern int RegionClear ();
extern int RegionSetValue (int bound1,int bound2);
extern int RegionRestoreValue ();
extern int RegionInfo ();
extern int RegionNeighbors ();
extern int RegionSavePar();
extern int RegionMark (Buffer data,int size1,int size2,int size3,int seed1,int seed2,int seed3,int min,int max,int neighborhood,Shadow list,int nlist);
extern int RegionMarkBorder (Buffer data,int size1,int size2,int size3);
extern int RegionUnMarkBorder (Buffer data,int size1,int size2,int size3,int Min,int Max);
extern int RegionDump ();

extern void RenderSize (int wide,int hite);
extern void RenderDraw ();
extern void set_data_lists();
extern void set_min_tol(float tol);
extern void set_max_tol(float tol);
extern void set_dtol(float tol);
extern float grab_min_tol();
extern float grab_max_tol();
extern float grab_dtol();
extern void RenderInit ();
extern void RenderHorz (Data data,Map hmap,Map vmap,Map zmap,Map map4,Map map5,int h0,int v0,int *margins,RenderAttr attr);
extern void RenderVert (Data data,Map hmap,Map vmap,Map zmap,Map map4,Map map5,int h0,int v0,int *margins,RenderAttr attr);
extern void RenderDeep (Data data,Map hmap,Map vmap,Map zmap,Map map4,Map map5,int h0,int v0,Render render,int *margins,RenderAttr attr);
extern void RenderDown (Data data,Map hmap,Map vmap,Map zmap,Map map4,Map map5,int h0,int v0,Render render,int *margins,RenderAttr attr);
extern int  RenderBufferValue (Render render,int x,int y);
extern int RenderShadowValue (Render render,int x,int y);
extern Buffer RenderBuffer2(Render render);
extern Buffer RenderBuffer (Render render);
extern int  RenderInfo (Render render);
extern void RenderSavePar ();
extern void RenderLine (Render render,int x0,int y0,int x1,int y1,int color);
extern void RenderSetInterp (int mode);
extern int  RenderTogglePolarity ();
extern void RenderSetHigh (int high);
extern void RenderSetLow (int low);
extern void RenderSetFenceTransp (int transparency);
extern void RenderToggleInterp ();
extern void RenderMap ();
extern void RenderClear ();
extern void RenderSetGradient (int vol_transp);
extern int  RenderImageDump ();
extern int  RenderMapDump ();
extern void RenderRect (int *h0,int *v0,int *nh,int *nv);
extern void RenderBasicHorz ARGS;
extern void RenderBasicVert ARGS;
extern void RenderShadowHorz ARGS;
extern void RenderShadowVert ARGS;
extern void RenderInterpHorz ARGS;
extern void RenderInterpVert ARGS;
extern void RenderTranspHorz ARGS;
extern void RenderTranspVert ARGS;
extern void RenderFrontFenceHorz ARGS;
extern void RenderTopFenceHorz ARGS;
extern void RenderSideFenceVert ARGS;
extern void RenderFrontFenceInterpHorz ARGS;
extern void RenderTopFenceInterpHorz ARGS;
extern void RenderSideFenceInterpVert ARGS;
extern int PlotFrontGrey();
extern int PlotSideGrey();
extern int PlotTopGrey();
extern int PlotFrontContour();
extern int PlotSideContour();
extern int PlotTopContour();
extern int PlotTopWiggle();
extern int PlotSideWiggle();
extern int PlotFrontWiggle();
extern int PrintFrontContour();
extern int PrintSideContour();
extern int PrintTopContour();
extern int PrintFrontGrey();
extern int PrintSideGrey();
extern int PrintTopGrey();
extern int PrintFrontWiggle();
extern int PrintSideWiggle();
extern int PrintTopWiggle();
extern int PrintCube();
extern int PlotCube();
extern int PlotView();
extern int PlotCom();
extern int BeginView();
extern int OverlayFinish(int cubeplot);
extern int SaveFront();
extern int SaveSide();
extern int SaveDeep();
extern int SaveTop();
extern int SaveAcross();
extern int SaveDown();
extern int PlotPlane (int across,int down,int deep,char *program,char *pipeto,char *file);
extern int PlotmyCube (int across,int down,int deep,char *program,char *pipeto,char *file);
extern int PlotExtractCube (Map hmap,Map vmap,Map zmap,Map map4,Map map5,float *buffer,int n1,int n2,int n3,int hdir,int vdir,int zdir);
extern int PlotExtractPlane (Map hmap,Map vmap,Map zmap,Map map4,Map map5,float *buffer,int n1,int n2,int hdir,int vdir);
extern int PlotExtractProfile (Map hmap,Map vmap,Map zmap,Map map4,Map map5,float *buffer,int n3,int zdir);

/* typed returns */
extern Display* UIDisplay();
extern int UIScreen();
extern XID UICanvasWindow();
extern XID UIBarWindow();
extern XID UIMainWindow();
extern int UIPikWrite();
extern void UIInit (int argc,char **argv);
extern void UIMain ();
extern int UITimer (int delay,XtTimerCallbackProc action);
extern int UIWindowInit (Widget parent);
extern int UIScreen ();
extern void UIMessage (Message message);
extern XFontStruct* UIFont (int size);
extern int UIFirst ();
extern int UIControlInit1 (Widget parent);
extern int UIAno (Widget widget,int item);
extern int UIDoDisplay (Widget widget,int item);
extern int UIDoDepend (Widget widget,int item);
extern int UIDoSearchMethod (Widget widget,int item);
extern void PikBest();
extern int UIDoCor (Widget widget,int item);
extern int UIClosePoly (Widget widget,int item);
extern int UIMovie (Widget widget,int item);
extern int UIDirection (Widget widget,int item);
extern int UIDirectionNoMove(Widget widget, int item);
extern int UILocalDirection();
extern int UIControlInit2 (Widget parent);
extern int UIGetToggle (Widget widget);
extern int UIToggleSet (Widget widget,int state);
extern int UIGetSlider (Widget widget);
extern int UISetSlider (Widget widget,float value);
extern int UImin_tol (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UImax_tol (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIdtol (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIwind (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIsradius (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIradius (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIpikj (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UInpath (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIFat (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIScale (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIRotate (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UISpeed (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIContrast (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIContrast0 (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int moveit ();
extern int UIStep ();
extern int UIResetContrast ();
extern int UISizeRaise ();
extern int UISizeInit ();
extern int UISizeDraw ();
extern int UISizeReset ();
extern int UISizeInitial ();
extern int UISizeClose ();
extern int UISizeSlider (Widget widget);
extern int UISizeText (Widget widget);
extern int UIArrayInit ();
extern int UIArrayRaise ();
extern int UIArrayDir (Widget widget,int item);
extern int UIArrayReset (int dir);
extern int UIArrayDraw ();
extern int UIArrayClose ();
extern int UIArrayEndAdjust ();
extern int UIArrayDeltaAdjust ();
extern int UIArrayShape (int n,int *across,int *down,int *delta);
extern int UILabelInit ();
extern int UIVplotInit ();
extern int UIFinishPanelRaise();
extern int UIVplotPanelRaise();
extern int UIFinishInit ();
extern int UIPikTextInit ();
extern int UIAnoTextInit ();
extern int UIPikTextRaise (char);
extern int UIAnoTextRaise ();
extern int UIDeleteTextAno();
extern int UIFinishTextAno();
extern int UIFinishSymbol();
extern int UIFinishSymbolDown();
extern int UIDeletePolyAno();
extern int UIFinishPolyAno();
extern int UIOrientRaise ();
extern int UIOrientReset ();
extern int UIOrientInit ();
extern int UIOrientDraw ();
extern int UIOrientClose ();
extern int UILabelRaise ();
extern int UILabelReset ();
extern int UILabelDraw ();
extern int UILabelClose ();
extern int UICloseVplot ();
extern int UITranspInit ();
extern int UITranspRaise ();
extern int UITranspClose ();
extern int UIFenceInit ();
extern int UITranspRate (Widget widget, int item);
extern int UITranspGradient (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UITranspHigh (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int  UITranspLow (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIFenceInit ();
extern int UIFenceTop ();
extern int UIFenceSide ();
extern int UIFenceFront ();
extern int UIFenceClose ();
extern int UIFenceRaise ();
extern int UIFenceClose ();
extern int UIFenceFront ();
extern int UIFenceSide ();
extern int UIFenceTop ();
extern int UIFenceOpacity (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIInfoInit ();
extern int UIInfo (char *text);
extern int UIInfoClose ();
extern int UISyzeRaise ();
extern int UISyzeInit ();
extern int UISyzeReset ();
extern int UISyzeClose ();
extern int UISyzeInitial ();
extern int UISyzeDraw ();
extern int UIMenuInit (Widget parent);
extern int UIStyleChoice (Widget widget,int item_in);
extern int UIColorChoice (Widget widget,int item);
extern int UIOverlayChoice (Widget widget,int item);
extern int UIMarkChoice (Widget widget,int item);
extern int UIBackgroundChoice (Widget widget,int item);
extern int UINeighborhoodChoice (Widget widget,int item);
extern int UIStatusChoice (Widget widget,int item);
extern int UIHelpChoice (Widget widget,int item);
extern int UIHelpPrint (char *start,char *finish);
extern int UIMouseInfo ();
extern int UIDumpFloats ();
extern int UIDumpFloats2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UIDumpBytes ();
extern int UIDumpBytes2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISavePar ();
extern int UISavePar2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISaveMessage (Message message);
extern int UIViewCommands ();
extern void ViewCommands ();
extern int UIQuit ();
extern int UISwapFrontSide ();
extern int UIDeepDump ();
extern int UIAcrossDump ();
extern int UIDownDump ();
extern int UIOrient0 ();
extern int UISwapSideExtra2();
extern int UISwapFrontExtra2();
extern int UISwapTopExtra2();
extern int UISwapSideExtra ();
extern int UISwapFrontExtra ();
extern int UISwapTopExtra ();
extern int UISwapTopFront ();
extern int UISwapSideTop ();
extern int UIFlipDown ();
extern int UIFlipAcross ();
extern int UIFlipDeep ();
extern int UIScreen0 ();
extern int UISize0 ();
extern int UIInterpolateToggle (Widget widget);
extern int UISizeChoice (Widget widget,int item);
extern int UIEditGrade ();
extern int UIPickClear (Widget widget,XButtonEvent event);
extern int UISmoothUndo ();
extern int UISubvolumeSmooth ();
extern int UIWakeup ();
extern int UIStatistics ();
extern int UIGradeUndo ();
extern int UIPikRead ();
extern int UIPikWrite2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UIPikRead2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISaveFront ();
extern int UISaveFront2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISaveSide ();
extern int UISaveSide2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISaveTop ();
extern int UISaveTop2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISaveDown ();
extern int UISaveDown2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISaveAcross ();
extern int UISaveAcross2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UISaveDeep ();
extern int UISaveDeep2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UIColorbarSize (int *wide,int *hite);
extern int UIDrawColorbar (Widget widget);
extern int UIDrawCanvas (Widget widget);
extern int UIDrawCanvasMovie (Widget widget);
extern int UIVZoomStart (Widget widget,XButtonEvent *event);
extern int UIHZoomStart (Widget widget,XButtonEvent *event);
extern int UIColorbarStart (Widget widget,XButtonEvent *event);
extern int UIZoomDrag (Widget widget,XButtonEvent *event);
extern int UIColorbarDrag (Widget widget,XButtonEvent *event);
extern int UIZoomEnd (Widget widget,XButtonEvent *event);
extern int UIFrameDrag (Widget widget,XButtonEvent *event);
extern int UISubvolumeDrag (Widget widget,XButtonEvent *event);
extern int UIZoomEnd (Widget widget,XButtonEvent *event);
extern int UIColorbarEnd (Widget widget,XButtonEvent *event);
extern int UIEraseStart (Widget widget,XButtonEvent *event);
extern int UIEraseDrag (Widget widget,XButtonEvent *event);
extern int UIEraseEnd (Widget widget,XButtonEvent *event);
extern int UIGrowStart (Widget widget,XButtonEvent *event);
extern int UIGrowDrag (Widget widget,XButtonEvent *event);
extern int UIGrowEnd (Widget widget,XButtonEvent *event);
extern int UIPikStart (Widget widget,XButtonEvent *event);
extern int UIPikDrag (Widget widget,XButtonEvent *event);
extern int UIPikEnd (Widget widget,XButtonEvent *event);
extern int UISubvolumeEnd (Widget widget,XButtonEvent *event);
extern int UIPick (Widget widget,XButtonEvent *event);
extern int UIFrameStart (Widget widget,XButtonEvent *event);
extern int UIFrameEnd (Widget widget,XButtonEvent *event);
extern int UISubvolumeStart (Widget widget,XButtonEvent *event);
extern int UIPickInsert (Widget widget,XButtonEvent *event);
extern int UIFinish (Widget widget,XButtonEvent *event);
extern int UIPikAdd (Widget widget,XButtonEvent *event);
extern int UIPikBest (Widget widget,XButtonEvent *event);
extern int UIReload (Widget widget,XButtonEvent *event);
extern int UIRun (Widget widget,XButtonEvent *event);
extern int UIFast (Widget widget,XButtonEvent *event);
extern int UIViewChangeb (Widget widget,XButtonEvent *event);
extern int UIViewChangef (Widget widget,XButtonEvent *event);
extern int UIOverlay (Widget widget,XButtonEvent *event);
extern int UISlow (Widget widget,XButtonEvent *event);
extern int UIPikMove (Widget widget,XButtonEvent *event);
extern int UIPikSymbol (Widget widget,XButtonEvent *event);
extern int UIPikDelete (Widget widget,XButtonEvent *event);
extern int UICanvasSize (int *wide,int *hite);

// DC06
extern int UIAcrossSmallX (Widget widget, XButtonEvent *event);
extern int UIDownSmallY (Widget widget, XButtonEvent *event);
extern int UIDeepSmallZ (Widget widget, XButtonEvent *event);
extern int UIAcrossLargeX (Widget widget, XButtonEvent *event);
extern int UIDownLargeY (Widget widget, XButtonEvent *event);
extern int UIDeepLargeZ (Widget widget, XButtonEvent *event);
extern int UICanvasResizing(int update);
extern int UICanvasRelocating(int update);
extern int UICanvasLocation(int *x, int *y);
extern int UIColorbarResizing(int update);
extern int UIColorbarRelocating(int update);
extern int UIColorbarLocation(int *x, int *y);
extern void UICanvasCheckUpdate(XtPointer ptr, XtIntervalId *id);
extern void UIColorbarCheckUpdate(XtPointer ptr, XtIntervalId *id);
extern int UIMotionOff(Widget widget);
extern int UIMotionRun();
extern int UIDelayMessage (Message message);
extern int UIDisplayDelayedMessage ();
extern int UIMenuToggleOnOff(Widget widget);
extern void UIMenuToggleUpdate(XtPointer ptr, XtIntervalId *id);

/** UI history list **/
extern int UIHistoryUndo(Widget widget, XButtonEvent *event);
extern int UIHistoryRedo(Widget widget, XButtonEvent *event);
extern int UIHistoryStart(Widget widget, XButtonEvent *event);
extern int UIHistoryEnd(Widget widget, XButtonEvent *event);
extern void UIHistoryAnimateUndoUpdate(XtPointer ptr, XtIntervalId *id);
extern void UIHistoryAnimateRedoUpdate(XtPointer ptr, XtIntervalId *id);
extern int UIHistoryAnimateOff(Widget widget);
extern int UIHistoryAnimateRun();
extern int UIHistoryAnimateUndo (Widget widget);
extern int UIHistoryAnimateRedo (Widget widget);
extern int UIHistorySave();
extern int UIHistorySave2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);
extern int UIHistoryLoad();
extern int UIHistoryLoad2 (Widget widget,XtPointer stuff,XmFileSelectionBoxCallbackStruct *cbs);

/** UI path view **/
extern int UIPathViewAnimateForward(Widget widget);
extern int UIPathViewAnimateBackward(Widget widget);
extern void UIPathViewAnimateForwardUpdate(XtPointer ptr, XtIntervalId *id);
extern void UIPathViewAnimateBackwardUpdate(XtPointer ptr, XtIntervalId *id);
extern int UIPathViewAnimateOff(Widget widget);
extern int UIPathViewAnimateRun();

/** UI round robin **/
extern int UIRoundRobinToggle(Widget widget);
extern int UIRoundRobinForward(Widget widget);
extern int UIRoundRobinBackward(Widget widget);

/** UI velocity view **/
extern int UIVelViewShiftLeft(Widget widget);
extern int UIVelViewShiftRight(Widget widget);
extern int UIVelViewScale (Widget widget,XtPointer client,XmScaleCallbackStruct *data);
extern int UIVelViewChoice (Widget widget,int item);
extern int UIPathViewToggleOnOff (Widget widget);
extern int UIPathViewStart (Widget widget);
extern int UIPathViewEnd (Widget widget);
extern int UIPathViewMiddle (Widget widget);
extern int UIPathViewForward (Widget widget);
extern int UIPathViewBackward (Widget widget);

/* typed returns */
extern void ViewChange(int step);
extern void ViewSingleSize (View view,Map hmap,Map vmap,Map zmap);
extern void ViewArray (View view,int nacross,int ndown,int across0,int dacross);
extern void ViewSize (Views views);
extern XtTimerCallbackProc ViewDrawTranspCallback (View view);
extern XtTimerCallbackProc ViewDrawMovie ();
extern void ViewDrawTransp (View view);
extern View ViewInit (char *tag,int iview);
extern void ViewsInit ();
extern void ViewDraw (View view,int mode);
extern void ViewDrawArray (View view);
extern View current_view();
extern int  num_views();
extern void ViewDrawPicks (View view);
extern void ViewDrawCube (View view,int mode);
extern void ViewDrawFence (View view,int mode);
extern void ViewDrawPlan (View view,int mode);
extern int ViewDrawAll ();
extern void ViewDrawPart (int mode);
extern int using_overlays();
extern Map ViewMap (View view,int index);
extern void ViewSetMovie (int movie);
extern Axis ViewDataAxis (View view,int imap);
extern int ViewSetFence (int mode);
extern int ViewSetTranspRate (int mode);
extern int ViewSetShape (int shape);
extern int ViewToggleFence (int mode);
extern int ViewSetFrames (int x,int y);
extern int ViewSetFrame (int index,int mode);
extern int ViewSetPick (int pick);
extern int ViewTogglePick ();
extern int ViewPick ();
extern int ViewMovie ();
extern Map ViewMovieMap (View view);
extern int ViewFramesOrigin ();
extern int ViewSwapAxis (int a,int b);
extern int ViewFlipAxis (int imap);
extern int ViewWindow (int x1,int y1,int x2,int y2,int hzoom,int vzoom);
extern int ViewWindow0 ();
extern void ViewInfo (View view);
extern void ViewSavePar (View view);
extern int ViewsOrient0 ();
extern int ViewOrient0(View view);
extern double Tyme();
extern void SetActiveView(int iview);
extern int ViewSize0();
extern int View3D();
extern int ViewSetStyle (int style);
extern int ViewStyleChoice (View view, int item);

/** history list **/
extern void ViewHistoryUndo(int draw);
extern void ViewHistoryRedo(int draw);
extern void ViewHistoryStart();
extern void ViewHistoryEnd();
extern int ViewHistoryAtStart();
extern int ViewHistoryAtEnd();
extern void ViewHistorySaveFile();
extern int ViewHistoryLoadFile();

/** round robin **/
extern void ViewRoundRobinToggle(int draw);
extern void ViewRoundRobinForward(int draw);
extern void ViewRoundRobinBackward(int draw);
extern void ViewRoundRobinUpdate(int draw);
/** path view **/
extern int ViewPathViewMove();

extern void PikInit();
extern int MovieSavePar ();
extern void PikDraw (int pik0,int draw);
extern void PikDrawBox (int x,int y,int size,int draw);
extern int  PikNear (int x,int y);
extern int PikCoord (int ipik,Plane plane,int *x,int *y);
extern int PikQuery (int x,int y);
extern void PikAdd (int x,int y);
extern void PikDelete (int x,int y);
extern void PikSymbol(void);
extern int PikUndo (void);
extern int PikInfo (void);
extern int PikSave (void);
extern void RegionInit (void);
extern int RegionSetLive (int live);
extern int RegionSetBound (int index,int ibound);
extern int RegionSetNeighborhood (int mode);
extern int RegionSetSeed (int *seed);
extern int RegionBound (int ibound);
extern int RegionSize ();
extern int RegionMark0 ();
extern int RegionFill (int *seed,int bound1,int bound2,int value);
extern int RegionClear ();
extern int RegionSetValue (int bound1,int bound2);
extern int RegionRestoreValue ();
extern int RegionInfo ();
extern int RegionNeighbors ();
extern int RegionSavePar();
extern int RegionMark (Buffer data,int size1,int size2,int size3,int seed1,int seed2,int seed3,int min,int max,int neighborhood,Shadow list,int nlist);
extern int RegionMarkBorder (Buffer data,int size1,int size2,int size3);
extern int RegionUnMarkBorder (Buffer data,int size1,int size2,int size3,int Min,int Max);
extern int RegionDump ();

extern int data_is_2d(Data data);
extern int grab_pik_j();
extern int grab_ano_fat();
extern int grab_ano_rotate();
extern int grab_do_ano();
extern int grab_n_ano();
extern int grab_last_op();
extern char grab_pik_info();
extern void set_pik_info(char *text);
extern void set_wind(int wind);
extern void set_display(int j);
extern void set_pikj(int j);
extern void set_path(int path);
extern void set_radius(int rad);
extern void set_depend(int depend);
extern int grab_depend();
extern void set_run_cor(int runcor);
extern void set_do_ano(int iano);
extern void set_close_status(int close, int arrow);
extern void set_ano_fat(int fat);
extern void set_ano_size(int isize);
extern int grab_pik_radius();
extern int grab_pik_nwind();
extern int grab_pik_npath();
extern int grab_run_cor();
extern int grab_ano_size();
extern int grab_search();
extern void set_search(int);
extern void set_ano_rotate(int irot);
extern void set_ano_text(char *text);
extern char *grab_ano_text();
extern void set_vplot_size(float xll, float xur, float yll, float yur);
extern int grab_do_close();
extern int grab_vplot_ncom();
extern char *grab_vplot_com(int icom);
extern int ViewFramesMiddle ();
extern int grab_do_ano();
extern int ViewMovieFullBounds ();
extern  void vit_max(int n1,int n2 ,int npath,float *in, int *out);
extern  void vit_min(int n1,int n2 ,int npath,float *in, int *out);
extern void wshspickr(int *j1path, float *dta,int n1,int n2,int *i1nail,int *i2nail,int nnail, int jwide,int jjump);
extern float wshspickrc(float *da,float *db,int ia,int ib,int n,int jwide);
extern void reorient(View view, int *norder);
extern int ReturnNdata();
void start_vel();
void change_loc();
void update_nmo();
int AxisStride_s (Axis axis);
Axis AxisInit3 (int dir,int stride,string label,int size,float first,float delta, float zoom);
void SetAxisStride_s(Axis axis,int istride);
void SetAxisStride(Axis axis,int istride);
void SetAxisLabel(Axis axis,string label);
void semb_init();
void dummy_init_view();
void dummy_loc_change();
void dummy_close_func();
void dummy_pik_change();
Data DataFromTag(char *tag);
int DataNumFromTag(char *tag);
int ViewNumFromTag(char *tag);
View ViewFromTag(char *tag);
int curent_view_num();
Axis CopyAxis(int dir, int stride, Axis oldaxis);
int ViewNumFromXY(int x, int y);

/*Pik Functions*/
extern int PikRead (Data data);
extern int PikWrite (char *filename,FILE *fd);

/*canvas stuff*/
extern int UIPikQuery (Widget widget,XButtonEvent *event);
extern int UIDrawIndLine (Widget widget,XButtonEvent *event);
extern int UIEraseIndLine (Widget widget,XButtonEvent *event);

/* grab param */
extern int rick_auxfetch( char *name, char *type, void* val, char* tag, char *extra);
extern int rick_auxgetch( char *name, char *type, void* val, char *extra);
extern int rick_getch( char *name, char *type, void* val);

extern int alloc_colormap(int ncolor);


/*Draw stuff*/
extern void set_color_table( int col, unsigned long ired,unsigned long  igreen,unsigned long  iblue, int base );
extern void DrawInit();
extern void DrawImage (Render render,int h0,int v0,int nh,int nv);
extern void DrawLine (int x1,int y1,int x2,int y2,int mode);
extern void SetFat(int fat);
extern void DrawOval(int x,int y,int width,int height,int mode);
extern void DrawArrow (int x1,int y1,int x2,int y2,int wide,int mode);
extern void DrawString (int x1,int y1,int angle,char *mys,int size,int mode);
extern void DrawBox (int x1,int y1,int x2,int y2,int mode);
extern void DraSheet (int x1,int y1,int x2,int y2,int mode);
extern void DrawColor (int color);
extern void DrawMask (long mask);
extern void DrawWindow (int window);
extern void DrawClear ();
extern void DrawColors (unsigned short *red,unsigned short *green,unsigned short *blue,int ncolor);
extern void DrawText (int x,int y,int align,char *text);
extern int DrawPixmap (int i);
extern void DrawColor1 (int index,float red,float green,float blue);
extern int DrawColorSize ();
extern int DrawColorBase();
extern int DrawSavePixmap (int i);
extern void DrawFreePixmaps ();
extern int DrawInfo ();
extern void DrawWatch (int mode);
extern int DrawDepth();
extern int DrawMaxColor();
extern int DrawNcolor();
extern int DrawOverlay();
extern void DrawOverlayToggle();
extern void  create_pad_image(int wide, int hite, Buffer input, Buffer output, 
  XImage *image);








                                                                                
                                                                                
void display_command(View view, char *command,int);
void OutputCommands(Views views) ;
void window_data(View view, int icom, char *command);
void transpose_data(View view, char *command,int);




extern void grab_cube_display(char*);

unsigned long truecolor_pixel[256];
Status xCreateRGBDefaultMap (Display *dpy, XStandardColormap *scmap);
unsigned long xGetFirstPixel (Display *dpy);
unsigned long xGetLastPixel (Display *dpy);
Colormap xCreateRGBColormap (Display *dpy, Window win,
   char *str_cmap, int verbose);
Colormap xCreateHSVColormap (Display *dpy, Window win,
   char *str_cmap, int verbose);
Colormap xCreateGrayColormap (Display *dpy, Window win);
Colormap xCreateHueColormap (Display *dpy, Window win);

#endif
