/* This file is automatically generated. DO NOT EDIT! */

#ifndef _divn_h
#define _divn_h


void divn_init(int ndim   /* number of dimensions */, 
	       int nd     /* data size */, 
	       int *ndat  /* data dimensions [ndim] */, 
	       int *nbox  /* smoothing radius [ndim] */, 
	       int niter1 /* number of iterations */);
/*< initialize >*/


void divn_close (void);
/*< free allocated storage >*/


void divn (float* num, float* den,  float* rat);
/*< smoothly divide rat=num/den >*/

#endif
