######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 8 23:16:59 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += qt_cube.pro
