#include <sepmath.h>
#include <cfortran.h>

FCALLSCSUB4(cefft,CEFFT,cefft,PVOID,INT,INT,FLOAT)
FCALLSCSUB5(cvfft,CVFFT,cvfft,PVOID,INT,INT,FLOAT,INT)
FCALLSCSUB5(refft,REFFT,refft,PVOID,INT,INT,FLOAT,INT)
FCALLSCSUB6(rvfft,RVFFT,rvfft,PVOID,INT,INT,INT,FLOAT,INT)

FCALLSCSUB4(cefft,CEFFT_,cefft_,PVOID,INT,INT,FLOAT)
FCALLSCSUB5(cvfft,CVFFT_,cvfft_,PVOID,INT,INT,FLOAT,INT)
FCALLSCSUB5(refft,REFFT_,refft_,PVOID,INT,INT,FLOAT,INT)
FCALLSCSUB6(rvfft,RVFFT_,rvfft_,PVOID,INT,INT,INT,FLOAT,INT)
